<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Masuk — BacaYuk</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap" rel="stylesheet"><script src="<?= base_url('assets/js/tailwind-play.js')?>"></script><style>*{box-sizing:border-box}body{margin:0;font-family:'DM Sans',sans-serif}.font-display{font-family:'Plus Jakarta Sans',sans-serif}input{color-scheme:light}</style></head>
<body class="min-h-dvh w-full overflow-x-hidden bg-[#FFF9ED] text-[#241B4B]">
<div class="mx-auto flex w-full max-w-[1536px] flex-col lg:min-h-dvh lg:flex-row">
<section class="relative flex w-full flex-col overflow-hidden bg-[#6554E8] px-6 pt-8 pb-10 sm:px-10 sm:pt-10 sm:pb-12 lg:min-h-dvh lg:w-1/2 lg:justify-between lg:px-16 lg:py-16">
<div class="pointer-events-none absolute -right-24 -top-24 hidden size-80 rounded-full bg-violet-400/30 lg:block"></div>
<div class="pointer-events-none absolute -bottom-24 -left-24 hidden size-80 rounded-full bg-violet-400/20 lg:block"></div>
<div class="relative z-10 mx-auto flex w-full max-w-xl flex-col lg:flex-1">
<div class="mb-12 flex shrink-0 items-center gap-3 text-lg font-bold text-white sm:mb-16"><div class="grid size-11 place-items-center rounded-xl bg-white text-[#6554E8]"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 6c-1.8-1.6-4-2-8-2v14c4 0 6.2.4 8 2 1.8-1.6 4-2 8-2V4c-4 0-6.2.4-8 2Z"/><path d="M12 6v14"/></svg></div><span class="font-display text-xl font-extrabold">BacaYuk</span></div>
<p class="text-[10px] font-semibold uppercase leading-4 tracking-[0.18em] text-violet-100 sm:text-xs sm:tracking-[0.22em]">Ruang tumbuh pembaca kecil</p>
<h1 class="font-display mt-4 max-w-full text-[clamp(2.25rem,10vw,3rem)] font-extrabold leading-[1.02] tracking-tight text-white sm:max-w-xl sm:text-5xl lg:text-6xl"><span class="block">Satu cerita,</span><span class="mt-3 block w-fit max-w-full rounded-2xl bg-[#FFF9ED] px-4 py-3 text-[clamp(2rem,9vw,2.75rem)] leading-[0.98] text-[#241B4B] sm:px-5 sm:text-[clamp(2rem,9vw,3.5rem)]">seribu imajinasi.</span></h1>
<p class="mt-6 hidden max-w-lg text-sm leading-6 text-violet-100 sm:block sm:text-base">Catat perjalanan membaca, rayakan setiap halaman, dan tumbuhkan kebiasaan hebat bersama BacaYuk.</p>
<div class="relative z-10 mt-8 flex min-h-[210px] items-end justify-center sm:mt-10 sm:min-h-[280px] lg:mt-4 lg:min-h-0 lg:flex-1">
<img src="<?= base_url('assets/3d/baca-anak-potong.png')?>" alt="Anak sedang membaca buku" class="relative z-10 block w-[min(70vw,280px)] max-w-full object-contain sm:w-[min(55vw,330px)] lg:w-[min(30vw,380px)]">
</div>
<p class="relative z-10 mt-5 hidden max-w-xs self-end text-sm leading-6 text-violet-100 lg:block">&ldquo;Membaca adalah jendela menuju dunia yang lebih luas.&rdquo;</p>
</div>
</section>
<main class="flex w-full flex-col items-center justify-start bg-[#FFF9ED] px-5 pt-10 pb-12 sm:px-8 sm:pt-14 sm:pb-16 lg:w-1/2 lg:justify-center lg:px-16 lg:py-16">
<div class="w-full max-w-[440px]">
<div class="mb-7 sm:mb-8"><p class="text-sm font-bold text-[#6554E8]">Selamat datang kembali &#128075;</p><h2 class="font-display mt-2 text-3xl font-extrabold leading-tight tracking-tight text-[#241B4B] sm:text-4xl">Masuk ke ruangmu</h2><p class="mt-3 text-sm leading-6 text-[#6F6A7D] sm:text-base">Lanjutkan cerita dan lihat progres membaca kamu.</p></div>
<div class="rounded-2xl bg-white p-5 shadow-[0_14px_40px_rgba(57,42,110,0.08)] sm:p-7">
<form method="post" action="<?= base_url('login')?>" class="space-y-5"><?= csrf_field()?>
<?php if(session()->getFlashdata('error')):?><div class="rounded-xl bg-[#FFE7EC] px-4 py-3 text-sm font-semibold text-[#A23C56]"><?= esc(session()->getFlashdata('error'))?></div><?php endif;?>
<?php if(session()->getFlashdata('success')):?><div class="rounded-xl bg-[#E7F7F2] px-4 py-3 text-sm font-semibold text-[#247A68]"><?= esc(session()->getFlashdata('success'))?></div><?php endif;?>
<label class="block"><span class="mb-2 block text-sm font-semibold text-slate-700">Username</span><input type="text" name="username" value="<?= esc(old('username'))?>" required autofocus autocomplete="username" class="h-12 w-full rounded-xl border border-[#DED9EE] bg-white px-4 text-sm text-slate-900 caret-[#6554E8] outline-none placeholder:text-slate-400 transition focus:border-[#6554E8] focus:ring-4 focus:ring-[#6554E8]/15" placeholder="Masukkan username"></label>
<label class="block"><span class="mb-2 block text-sm font-semibold text-slate-700">Kata sandi</span><span class="relative block"><input type="password" id="sandi" name="password" required autocomplete="current-password" class="h-12 w-full appearance-none rounded-xl border border-[#DED9EE] bg-white px-4 pr-12 text-sm text-slate-900 caret-[#6554E8] outline-none placeholder:text-slate-400 transition focus:border-[#6554E8] focus:ring-4 focus:ring-[#6554E8]/15" placeholder="Masukkan kata sandi"><button type="button" id="intip" aria-label="Tampilkan kata sandi" class="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-[#6554E8]"><svg id="mata-buka" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg><svg id="mata-tutup" class="hidden" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c6.5 0 10 8 10 8a18.5 18.5 0 0 1-2.16 3.19M6.61 6.61A13.5 13.5 0 0 0 2 12s3.5 8 10 8a9.74 9.74 0 0 0 5.39-1.61"/><path d="M2 2l20 20"/><path d="M9.88 9.88a3 3 0 1 0 4.24 4.24"/></svg></button></span></label>
<button class="mt-6 h-12 w-full rounded-xl bg-[#6554E8] px-5 text-sm font-bold text-white shadow-lg shadow-[#6554E8]/20 transition hover:bg-[#5847D8] focus:outline-none focus:ring-4 focus:ring-[#6554E8]/20 active:scale-[0.99]">Masuk ke BacaYuk <span>&rarr;</span></button>
</form>
</div>
<div class="mt-5 rounded-2xl bg-[#F0EBFF] p-5 sm:p-6"><div class="mb-3 flex items-center justify-between"><p class="font-display text-sm font-bold">Coba akun demo</p><span class="text-xs font-semibold text-[#6554E8]">Untuk eksplorasi</span></div><div class="grid grid-cols-1 gap-2 sm:grid-cols-3"><div class="rounded-xl bg-white/70 py-2.5 text-center text-xs"><b class="block">Admin</b><span class="text-[#6F6A7D]">admin</span></div><div class="rounded-xl bg-white/70 py-2.5 text-center text-xs"><b class="block">Guru</b><span class="text-[#6F6A7D]">guru</span></div><div class="rounded-xl bg-white/70 py-2.5 text-center text-xs"><b class="block">Siswa</b><span class="text-[#6F6A7D]">siswa</span></div></div><p class="mt-3 text-center text-[11px] text-[#6F6A7D]">Password demo: admin123 &middot; guru123 &middot; siswa123</p></div>
<p class="mt-6 text-center text-xs text-[#9B96A5]">SDN Grogol Utara 09 &middot; Kelas IV</p>
</div>
</main>
</div>
<script>document.getElementById('intip').addEventListener('click',function(){var s=document.getElementById('sandi');var buka=s.type==='password';s.type=buka?'text':'password';document.getElementById('mata-buka').classList.toggle('hidden',buka);document.getElementById('mata-tutup').classList.toggle('hidden',!buka);this.setAttribute('aria-label',buka?'Sembunyikan kata sandi':'Tampilkan kata sandi');});</script>
</body></html>
